### ISSUE TITLE
Inaccurate description of steering signals in README.md

### ISSUE THREAD

**Issue by BenGravell** [commaai/comma-steering-control#1]
Hi, I was reading the README.md and noticed it looks like the descriptions for `latAccelSteeringAngle` and `latAccelDesired` got swapped in the table.

|    | Fields                | Description                                                                      | Value Range     |
|---:|:----------------------|:---------------------------------------------------------------------------------|:----------------|
|  9 | latAccelSteeringAngle | Lateral acceleration requested from the planner                                  | [-∞, ∞]         |
| 10 | latAccelDesired       | Lateral acceleration computed from the steering wheel angle and vehicle dynamics | [-∞, ∞]         |

**Comment by nuwandavek** [comment]
Good find! Fixed in https://github.com/commaai/comma-steering-control/commit/e67a51ce3cc26477303b2fd4dbebdf008ab01eaa
